"""Core data structures for the SCID dual-LM runtime."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any, Literal


SCIDScore = Literal["?", "1", "2", "3"]
SCIDAction = Literal["advance", "clarify", "reask", "branch", "crisis"]
SCIDInteractionRoute = Literal[
    "scid_answer",
    "scid_partial",
    "question_clarification",
    "meta_question",
    "off_sop_chat",
    "resume_scid",
    "pause_scid",
    "stop_scid",
    "crisis",
]
SCIDInteractionMode = Literal["scid", "off_sop_chat", "paused", "crisis", "completed"]

VALID_SCORES: set[str] = {"?", "1", "2", "3"}
VALID_ACTIONS: set[str] = {"advance", "clarify", "reask", "branch", "crisis"}
VALID_INTERACTION_ROUTES: set[str] = {
    "scid_answer",
    "scid_partial",
    "question_clarification",
    "meta_question",
    "off_sop_chat",
    "resume_scid",
    "pause_scid",
    "stop_scid",
    "crisis",
}


def utc_now_iso() -> str:
    """Return a UTC timestamp string."""

    return datetime.utcnow().isoformat()


def normalize_score(value: Any) -> SCIDScore:
    """Normalize SCID score labels.

    The legacy prototype used ``0`` for "资料不足"; SCID form conventions use
    ``?``. Keep accepting ``0`` at boundaries, but never store it internally.
    """

    text = str(value).strip()
    if text in {"?", "？", "0", "资料不足", "unknown", "insufficient"}:
        return "?"
    if text in {"1", "2", "3"}:
        return text  # type: ignore[return-value]
    raise ValueError(f"Invalid SCID score: {value!r}")


@dataclass(slots=True)
class SCIDField:
    """One runnable SCID assessment field."""

    field_id: str
    question_text: str
    section: str
    source_qid: str | None = None
    target_field_id: str | None = None
    module: str | None = None
    kind: str = "scan"
    tag: str = ""
    options: dict[str, str] = field(
        default_factory=lambda: {
            "?": "资料不足",
            "1": "无或否",
            "2": "阈下",
            "3": "阈上或是",
        }
    )

    def snapshot(self) -> dict[str, Any]:
        """Return a JSON-friendly representation."""

        return asdict(self)


@dataclass(slots=True)
class SCIDTemplate:
    """A runnable subset of a SCID interview graph."""

    template_id: str
    fields: dict[str, SCIDField]
    scan_order: list[str]
    priority_modules: tuple[str, ...] = ("F", "G", "K")
    scan_field_by_target: dict[str, str] = field(default_factory=dict)

    def first_field_id(self) -> str:
        """Return the first runnable field."""

        if not self.scan_order:
            raise ValueError("SCID template has no scan fields")
        return self.scan_order[0]

    def get_field(self, field_id: str) -> SCIDField:
        """Return one field by id."""

        try:
            return self.fields[field_id]
        except KeyError as exc:
            raise KeyError(f"Unknown SCID field: {field_id}") from exc

    def snapshot(self) -> dict[str, Any]:
        """Return a compact JSON-friendly template snapshot."""

        return {
            "template_id": self.template_id,
            "scan_order": list(self.scan_order),
            "priority_modules": list(self.priority_modules),
            "field_count": len(self.fields),
        }


@dataclass(slots=True)
class SCIDFieldState:
    """Filled state for one SCID field."""

    field_id: str
    score: SCIDScore
    confidence: float
    evidence: list[str]
    raw_user_text: str
    reasoning_summary: str
    turn_id: int
    updated_at: str = field(default_factory=utc_now_iso)

    def snapshot(self) -> dict[str, Any]:
        """Return a JSON-friendly state snapshot."""

        return asdict(self)


@dataclass(slots=True)
class AssessmentDecision:
    """Validated decision emitted by the background diagnostic LM."""

    field_id: str
    score: SCIDScore | None
    confidence: float
    evidence: list[str]
    next_action: SCIDAction
    clarification_question: str
    reasoning_summary: str
    raw_payload: dict[str, Any] = field(default_factory=dict)

    def snapshot(self) -> dict[str, Any]:
        """Return a JSON-friendly decision snapshot."""

        return asdict(self)


@dataclass(slots=True)
class SCIDRouteDecision:
    """Backend route decision made before any SCID field scoring."""

    route: SCIDInteractionRoute
    confidence: float
    should_score: bool
    normalized_user_text: str
    safe_frontend_content: str
    reasoning_summary: str
    raw_payload: dict[str, Any] = field(default_factory=dict)

    def snapshot(self) -> dict[str, Any]:
        """Return a JSON-friendly decision snapshot."""

        return asdict(self)


@dataclass(slots=True)
class DialogueDirective:
    """Safe frontend-LM instruction generated by the SCID orchestrator."""

    directive_type: str
    field_id: str | None
    question_text: str
    instruction: str
    progress_text: str = ""
    safety_note: str = ""
    allowed_actions: list[str] = field(
        default_factory=lambda: ["ask", "clarify_wording", "respect_stop"]
    )

    def snapshot(self) -> dict[str, Any]:
        """Return a JSON-friendly directive snapshot."""

        return asdict(self)


@dataclass(slots=True)
class SCIDTurn:
    """One user turn tracked by the assessment ledger."""

    turn_id: int
    field_id: str | None
    user_text: str
    assistant_text: str = ""
    decision: dict[str, Any] | None = None
    created_at: str = field(default_factory=utc_now_iso)

    def snapshot(self) -> dict[str, Any]:
        """Return a JSON-friendly turn snapshot."""

        return asdict(self)


@dataclass(slots=True)
class SCIDInteractionTurn:
    """One user-facing interaction before optional SCID scoring."""

    interaction_seq: int
    user_text: str
    interaction_mode: str
    route_decision: dict[str, Any] | None = None
    assistant_text: str = ""
    scid_turn_id: int | None = None
    stale: bool = False
    ignored_reason: str = ""
    created_at: str = field(default_factory=utc_now_iso)

    def snapshot(self) -> dict[str, Any]:
        """Return a JSON-friendly turn snapshot."""

        return asdict(self)
